### PR TITLE
Resolve script errors raised during the RPL regression tests on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by yatch**
This PR resolves the script errors which prevent you from performing regression tests for RPL on Ubuntu 14.04, which Instant Contiki 3.0 is based on.

The script errors look like this:

```shell
...
FATAL [Thread-7] (LogScriptEngine.java:312) - Test script error, terminating Cooja.
FATAL [Thread-7] (LogScriptEngine.java:313) - Script error:
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy5.run(Unknown Source)
	at org.contikios.cooja.plugins.LogScriptEngine$4.run(LogScriptEngine.java:300)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.PrivilegedActionException: javax.script.ScriptException: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot find function substr in object *. (<Unknown source>#92) in <Unknown sourceat line number 92
...
Caused by: javax.script.ScriptException: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot find function substr in object *. (<Unknown source>#92) in <Unknown sourceat line number 92
...
Caused by: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot find function substr in object *. (<Unknown source>#92)
...
 FAIL ಠ_ಠ
```

In this case, the error occurs on evaluating `packets.substr(0, num)` at the following statement.

```javascript
packets = packets.substr(0, num) + "*";
```

At this point, `packets` on the right side is supposed to be `"*"`, a String object. Howerver, it is, in fact, a [ConsString](https://mozilla.github.io/rhino/javadoc/org/mozilla/javascript/ConsString.html) object which does not have the `substr` function. `packets.substr(0, num) + "*"` does not produce a String object in the first iteration under the Java environment by openjdk-7-jdk on Ubuntu 14.04.

One of solutions to overcome this error is using the `concat` function instead of the `+` operator. This is the key idea of this patch.

```javascript
packets = packets.substr(0, num).concat("*");
```

With the tip of the master branch, `regression-tests/12-rpl/summary` would have these results in it after the regression tests.

```
07-rpl-random-rearrangement.testlog:TEST OK
01-rpl-up-route.1.faillog: FAIL ಠ_ಠ
02-rpl-root-reboot.1.faillog: FAIL ಠ_ಠ
03-rpl-28-hours.1.faillog: FAIL ಠ_ಠ
04-rpl-large-network.1.faillog: FAIL ಠ_ಠ
05-rpl-up-and-down-routes.1.faillog: FAIL ಠ_ಠ
06-rpl-temporary-root-loss.1.faillog: FAIL ಠ_ಠ
08-rpl-dao-route-loss-0.1.faillog: FAIL ಠ_ಠ
08-rpl-dao-route-loss-1.1.faillog: FAIL ಠ_ಠ
08-rpl-dao-route-loss-2.1.faillog: FAIL ಠ_ಠ
08-rpl-dao-route-loss-3.1.faillog: FAIL ಠ_ಠ
08-rpl-dao-route-loss-4.1.faillog: FAIL ಠ_ಠ
08-rpl-dao-route-loss-5.1.faillog: FAIL ಠ_ಠ
09-rpl-probing.1.faillog: FAIL ಠ_ಠ
10-rpl-multi-dodag.1.faillog: FAIL ಠ_ಠ
```

Applying the patch, all the tests under `regression-tests/12-rpl` succeed:

```
01-rpl-up-route.testlog:TEST OK
02-rpl-root-reboot.testlog:TEST OK
03-rpl-28-hours.testlog:TEST OK
04-rpl-large-network.testlog:TEST OK
05-rpl-up-and-down-routes.testlog:TEST OK
06-rpl-temporary-root-loss.testlog:TEST OK
07-rpl-random-rearrangement.testlog:TEST OK
08-rpl-dao-route-loss-0.testlog:TEST OK
08-rpl-dao-route-loss-1.testlog:TEST OK
08-rpl-dao-route-loss-2.testlog:TEST OK
08-rpl-dao-route-loss-3.testlog:TEST OK
08-rpl-dao-route-loss-4.testlog:TEST OK
08-rpl-dao-route-loss-5.testlog:TEST OK
09-rpl-probing.testlog:TEST OK
10-rpl-multi-dodag.testlog:TEST OK
```

From here, I'd like to provide some background information.

First of all, on Ubuntu 12.04, this error does not occur. `packets.substr(0, num) + "*"` returns a String object. This is why this type of error is not found on Travis CI tests which uses Ubuntu 12.04.

I noticed a difference between Ubuntu 12.04 and 14.04; this is the version of Rhino that is installed with openjdk-7-jdk: 1.7R3 on Ubuntu 12.04 and 1.7R4 on Ubuntu 14.04. Here is the environmental information of my Ubuntu 12.04 machine and 14.04 machine (Instant Contiki 3.0 without `apt-get upgrade`):

```shell
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
# java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
# jrunscript -q
Language ECMAScript 1.7 implemention "Rhino" Rhino 1.7 release 3 2012 02 16

```

```shell
user@instant-contiki:~/contiki$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
user@instant-contiki:~/contiki$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK Client VM (build 24.79-b02, mixed mode, sharing)
user@instant-contiki:~/contiki$ jrunscript -q
Language ECMAScript 1.7 implemention "Rhino" Rhino 1.7 release 4 2013 08 27
```

According to [the release note of Rhino 17R4](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/New_in_Rhino_1.7R4), there is some improvement on string concatenation. It says:

> Make string concatenation with + fast.

It seems like the following feature found in [the ConsString document](https://mozilla.github.io/rhino/javadoc/org/mozilla/javascript/ConsString.html)  has been introduced since Rhino 1.7R4.

> This string representation is optimized for concatenation using the "+" operator. Instead of 
> immediately copying both components to a new character array, ConsString keeps references to 
> the original components and only converts them to a String if either toString() is called or a certain 
> depth level is reached.

The conclusion is that this improvement on the `+` operator causes the errors raised in the regression tests on Ubuntu 14.04 (Rhino 1.7R4).

Lastly, I'll share a proof-of-concept.

We can get the same error as mentioned above by `jrunscript` (Rhino 1.7R4/Ubuntu 14.04). In the last part of this example, you can see the `concat` function works as expected.
```shell
$ jrunscript -q
Language ECMAScript 1.7 implemention "Rhino" Rhino 1.7 release 4 2013 08 27
$ jrunscript   
js> var packets = "_________";
js> packets = packets.substr(0, 0) + "*";
*
js> packets = packets.substr(0, 1) + "*";
script error: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot find function substr in object *. (<STDIN>#1) in <STDIN> at line number 1
js> packets.getClass()
class sun.org.mozilla.javascript.ConsString
js>
$ jrunscript
js> var packets = "_________";
js> packets = packets.substr(0, 0).concat("*");
*
js> packets = packets.substr(0, 1).concat("*");    
**
```

This example shows the `concat` method works on Rhino 1.7R3 (Ubuntu 12.04) in the same way as shown above with Rhino 1.7R4.
```shell
# jrunscript -q
Language ECMAScript 1.7 implemention "Rhino" Rhino 1.7 release 3 2012 02 16
# jrunscript
js> var packets = "_________";
js> packets = packets.substr(0, 0).concat("*");
*
js> packets = packets.substr(0, 1).concat("*");
**
```

### CODE REVIEW

**Comment by simonduq** [comment]
Awesome, I've been annoyed with this issue many times! Thanks for investigating and fixing. :+1:

**Comment by alignan** [comment]
Thanks for the thoughtful explanation and fix :+1:
